name: Build and Deploy
on: 
  push:
    branches:
      - addSpecFiles
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone comobi-core repository
        run: |
          git clone -b addSpecFiles --depth 1 https://github.com/betagouv/comobi-core.git .

      - name: Clone specific repository
        run: |
          git clone --depth 1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY specific
      - name: move specific files
        run: |
          mv specific/ .
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build:direct
      - name: Build and Push Jekyll site
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'deploy'
          jekyll_src: .
      
